### ISSUE TITLE
cannot use define string "elif"

### ISSUE THREAD

**Issue by TechD-Robin** [Chris--A/ShiftLCD_Fixed#1]
When compile sample code by your fixed code, maybe get error on 'Arduino IDE Ver 1.6.5',
will get the error on ShiftLCD.h Line: 124 & ShiftLCD.cpp Line: 259, 
maybe this compiler unlike "#elif". 
so, must change to #else .

Just, that your know this message.

Thanks for your fix of the library. ^^~

**Comment by Chris--A** [comment]
Cheers, I only updated the headers and didn't really look through the code.
Thanks for pointing it out, I'll update the code and release a new version.

**Comment by Chris--A** [comment]
This is now fixed. Thank you.
I might clone this repo now and add it to the IDE library manager so it can be directly downloaded.
